show nginx logs after run

diff --git a/.github/workflows/tests-develop.yml b/.github/workflows/tests-develop.yml
--- a/.github/workflows/tests-develop.yml
+++ b/.github/workflows/tests-develop.yml
@@ -69,7 +69,7 @@ jobs:
 
       - name: Print NGINX Error Logs on Failure
         shell: bash
-        run: cat .github/proxy/logs/error.log .github/proxy/logs/access.log 2>/dev/null || echo "Log files missing."
+        run: cat logs/error.log logs/access.log 2>/dev/null || echo "Log files missing."
 
   build:
     env:
